#import <JFFAsyncOperations/JFFAsyncOperationsBlockDefinitions.h>

JFFAsyncOperation asyncOperationWithSyncOperation( JFFSyncOperation loadDataBlock_ );
JFFAsyncOperation asyncOperationWithSyncOperationAndQueue( JFFSyncOperation loadDataBlock_, NSString* queueName_ );

JFFAsyncOperation asyncOperationWithSyncOperationWithProgressBlock( JFFSyncOperationWithProgress progressLoadDataBlock_ );
