#import <JFFAsyncOperations/JFFAsyncOperationsBlockDefinitions.h>

JFFAsyncOperation asyncOperationWithSyncOperation( JFFSyncOperation loadDataBlock_ );

JFFAsyncOperation asyncOperationWithSyncOperationWithProgressBlock( JFFSyncOperationWithProgress progressLoadDataBlock_ );
